### ISSUE TITLE
Warnings about not using in production 

### ISSUE THREAD

**Issue by gudleik** [Skalar/pronto-image-classifer#2]
When spinning up the docker image, it spits out some warnings about not using in production

```
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
```

Expected behaviour: should be production ready

**Comment by joshclement0** [comment]
Made this production ready using the library waitress. Not sure if this is the best solution, will keep looking into it
