### ISSUE TITLE
Retraining the model

### ISSUE THREAD

**Issue by gudleik** [Skalar/pronto-image-classifer#5]
Readme says to use create_model.py to retrain the model, but not how ;)
Tried running `python3 create_model.py` without luck. Got error `ModuleNotFoundError: No module named 'pandas'`.

Document the steps required to retrain the model, including 
- how to install required dependencies
- how to run the script
- what to do after, is it enough to just rebuild the docker image?

**Comment by joshclement0** [comment]
I made the README a little clearer
