### ISSUE TITLE
Speed improvements

### ISSUE THREAD

**Issue by gudleik** [Skalar/pronto-image-classifer#9]
Currently the Api is rather slow. Predicting the sample image on my Macbook takes about a second (my internet speed is 500mbps). And in production this would take a lot more time as our production nodes are pretty slow.

Are there any ways to improve this?
If not, it will limit how we can use the service. For example, it will be impossible to provide "live" feedback to the user (ie user uploads images and is presented the tags in the same modal). So we most likely will have to run it in the background.

**Comment by joshclement0** [comment]
There is an option of loading the model into a script tag on html, I would make the speed and concurrency dependent on their browser (and computer). This would mean a lot of work for integration and wouldn't make it a separate endpoint. 

I could also make it so we accept an image as a parameter not a url, that would also help with the speed, especially if it was already resized.

**Comment by gudleik** [comment]
> There is an option of loading the model into a script tag on html, I would make the speed and concurrency dependent on their browser (and computer). This would mean a lot of work for integration and wouldn't make it a separate endpoint.

Not sure if I understood this correctly. Which html are you referring to?

> I could also make it so we accept an image as a parameter not a url, that would also help with the speed, especially if it was already resized

You mean posting the image as binary data to the api, so the api don't have to fetch the image from S3?
I would prefer passing url as it is now. Its a lot easier to test and debug. Passing huge chunks of binary data around as parameters can also be prone to issues (ie in some cases nginx needs to be configured to allow this).
How sensitive is the image recognition to image sizes/resolution? If the image is resized too much, we loose details(?)
We already use a service for resizing images (imgix.com). We could add a specific resizer for tensorflow images, if that would make a huge difference.

**Comment by joshclement0** [comment]
This would have to be added along with the desired image tag
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
And the JS would include something like this
> import * as tf from '@tensorflow/tfjs';
> const model = await tf.loadLayersModel( EndpointforSavedModel );
> const example = tf.fromPixels(imageHTMLElement);  // for example
> const prediction = model.predict(example);

**Comment by joshclement0** [comment]
The resolution that is used is 224x224. Adding a specific resizer might make a big difference.

**Comment by gudleik** [comment]
After more testing it seems as speed is not such a big problem after all. Closing this issue.
